### ISSUE TITLE
Enhancement: JSON return type

### ISSUE THREAD

**Issue by timscreep** [2IMT/polycat#17]
### There is a thing in the waybar documentation that allows you to customize the appearance from the returned values.

![Image](https://github.com/user-attachments/assets/97f2c54f-0b9d-4716-8465-800ddf09320c)
https://github.com/Alexays/Waybar/wiki/Module:-Custom#module-custom-config-return-type

Let's assume in the polycat config we can set which class is returned and at what value. (Conventionally, 0-30 = low, 30-60 = mid, 60+ = high).
and in style.css waybar we can write something like:
```css
#custom-polycat.low{
    color: @green
}
#custom-polycat.mid{
    color: @yellow
}
#custom-polycat.high{
    color: @red
}
```

### so that the user himself sets at what values ​​which class is returned. _What if a person wants each percentage for its own color?_
